In [1]:
import numpy as np

In [2]:
array_in_numpy = np.array([1, 2, 3, 4])

In [3]:
array_in_numpy

array([1, 2, 3, 4])

In [7]:
matrix_in_numpy = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [8]:
print(matrix_in_numpy)

[[1 2 3 4]
 [5 6 7 8]]


In [9]:
matrix_in_numpy + 1

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [11]:
matrix_in_numpy.shape

(2, 4)

In [12]:
array_in_numpy.shape

(4,)

Khởi tạo giá trị ma trận

In [13]:
matrix_0 = np.zeros((2, 4))

In [14]:
matrix_0

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
vector_0 = np.zeros(10)

In [16]:
vector_0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
vector_0.shape

(10,)

In [19]:
matrix = np.ones(3, 3)

TypeError: Cannot interpret '3' as a data type

In [20]:
matrix = np.ones((3, 3), 0)

TypeError: Cannot interpret '0' as a data type

In [21]:
matrix = np.ones((3, 3))

In [22]:
matrix

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
matrix = np.zeros((3, 3))

In [24]:
matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
array_in_numpy[0]

np.int64(1)

In [30]:
array_in_numpy[-1]

np.int64(4)

In [31]:
array_in_numpy[0:2]

array([1, 2])

In [32]:
array_in_numpy[2:4]

array([3, 4])

In [33]:
array_in_numpy[2:]

array([3, 4])

In [34]:
matrix_in_numpy[0][2]

np.int64(3)

In [35]:
matrix_in_numpy[1][3]

np.int64(8)

In [36]:
matrix_in_numpy[1][-1]

np.int64(8)

In [37]:
matrix_in_numpy[0:2, 1:3]

array([[2, 3],
       [6, 7]])

In [38]:
matrix_in_numpy[:, 1:3]

array([[2, 3],
       [6, 7]])

In [40]:
matrix_in_numpy

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [41]:
sliced_matrix = matrix_in_numpy[:, 1:3]

In [42]:
sliced_matrix

array([[2, 3],
       [6, 7]])

In [54]:
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [55]:
print(array[:, 1:3])

[[2 3]
 [6 7]]


In [56]:
matrix_in_numpy[1].shape

(4,)

In [57]:
matrix_in_numpy[0, :].shape

(4,)

In [58]:
matrix_in_numpy > 2

array([[False, False,  True,  True],
       [ True,  True,  True,  True]])

In [59]:
matrix_in_numpy[matrix_in_numpy > 2]

array([3, 4, 5, 6, 7, 8])

In [61]:
matrix_in_numpy[matrix_in_numpy > 2] = 4

In [62]:
matrix_in_numpy

array([[1, 2, 4, 4],
       [4, 4, 4, 4]])

In [63]:
matrix_in_numpy.shape

(2, 4)

In [64]:
matrix_in_numpy.reshape((4, 2))

array([[1, 2],
       [4, 4],
       [4, 4],
       [4, 4]])

In [65]:
matrix_in_numpy.reshape((8, 1))

array([[1],
       [2],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4]])

In [67]:
matrix_in_numpy.reshape((8, 2))

ValueError: cannot reshape array of size 8 into shape (8,2)

Numpy và một số phép tính toán

In [68]:
matrix_in_numpy

array([[1, 2, 4, 4],
       [4, 4, 4, 4]])

In [69]:
np.sqrt(matrix_in_numpy)

array([[1.        , 1.41421356, 2.        , 2.        ],
       [2.        , 2.        , 2.        , 2.        ]])

In [71]:
np.abs(np.array([[-1, 1]]))

array([[1, 1]])

In [72]:
np.floor([[1.2, 1.7]])

array([[1., 1.]])

In [73]:
np.ceil([[1.2, 1.7]])

array([[2., 2.]])

In [74]:
np.modf([[1.2, 1.7]])

(array([[0.2, 0.7]]), array([[1., 1.]]))

Đường dẫn tham khảo các hàm tương tự:

https://numpy.org/doc/stable/reference/routines.math.html