Để chứng minh công thức tính tổng dãy số dương từ 1 đến (n), ta sử dụng công thức sau:

S = 1 + 2 + 3 + … + n

Công thức này có thể được chứng minh bằng phương pháp quy nạp hoặc sử dụng một cách tiếp cận thông minh do Gauss tìm ra. Ở đây, tôi sẽ trình bày cách tiếp cận của Gauss:

Giả sử ta có một dãy số từ 1 đến (n), ta viết lại dãy số đó theo thứ tự ngược lại:

S = n + (n - 1) + (n - 2) + … + 1

Khi cộng mỗi cặp số ở hai đầu của dãy số, tức là (1 + n), (2 + (n-1)), và cứ tiếp tục như vậy, ta thấy rằng tổng của mỗi cặp luôn bằng (n + 1). Vì có tổng cộng (n) số, và mỗi số được cộng đôi một lần, ta có thể nhận ra rằng tổng cuối cùng sẽ là:

S = n(n+1) ÷ 2


Đây chính là công thức để tính tổng của dãy số dương từ 1 đến (n), và nó được chứng minh thông qua việc cộng đối xứng các phần tử trong dãy số.

In [ ]:
aSum = 0
for i in range(1, 6):
  aSum += i

print(aSum)


15


In [ ]:
aSum = 0
for i in range(1, 5):
  aSum += i

print(aSum)


10


In [ ]:
aSum = 0
i = 1
while i < 6:
  aSum += i
  i += 1

print(aSum)


15


In [ ]:
def calSum(n):
    # Lập trình tại đây
    y = 0
    if 1 <= n <= 10**4:
        for i in range(n):
            y +=i+1
    return y


print(calSum(20))
print(calSum(10))


210
55


In [ ]:
import numpy as np
v = np.array([1, 2, 3])

In [ ]:
v

array([1, 2, 3])

In [ ]:
# 11 norm of a vector
from numpy import array
from numpy.linalg import norm
a = np.array([1, 1])
x = norm(a, 1)
y = norm(a, 2)
print(x, y)

2.0 1.4142135623730951


In [ ]:
import numpy as np

def exercise1():
    # Định nghĩa x
    x = np.array([1, 2, 3])

    # Định nghĩa y
    y = np.array([-1, -2, 3])

    # Tính chuẩn x và gán vào biến x_norm2
    x_norm2 = 0
    for i in x:
        x_norm2 += i**2
    x_norm2 = np.sqrt(x_norm2)
    # Tính chuẩn y và gán vào biến y_norm2
    y_norm2 = 0
    for i in y:
        y_norm2 += i**2
    y_norm2 = np.sqrt(y_norm2)

    return [round(x_norm2, 2), round(x_norm2, 2)]

x_norm2, y_norm2 = exercise1()
print(round(x_norm2, 2), round(y_norm2,2))

3.74 3.74


In [ ]:
import numpy as np
y = np.array([1, 2, 3])
x = np.array([2, 3, 4])
print(x + y)

[3 5 7]


In [ ]:
print(x - y)
print(x / y)
print(2*x - 3*y)

[1 1 1]
[2.         1.5        1.33333333]
[ 1  0 -1]


In [ ]:
x = np.array([0, 1, 2, 3])
y = np.array([-2, -6, -7, 5])
print(2*x, '+', 2*y, '=', 2*x + 2*y)

[0 2 4 6] + [ -4 -12 -14  10] = [ -4 -10 -10  16]


# 1.3 Phép nhân Vector
Có 2 kiểu nhân Vector là: phép Dot product và Hadamard product

# 1.3.1 Dot product
Tích của 2 vector sẽ là một vô hướng (scalar).

In [ ]:
y = np.array([-1, 2, -3])
x = np.array([2, -3, 4])
np.dot(y, x)
# -1 * 2 + 2 * (-3) + (-3) * 4

np.int64(-20)

In [ ]:
y.dot(x)
x.dot(y)

np.int64(-20)

In [ ]:
x @ y

np.int64(-20)

# 1.3.2 Hadamard product
Hadamard product sẽ thực hiện phép nhân elementwise để tạo ra vector mới.

In [ ]:
import numpy as np
from numpy import dot
from numpy.linalg import norm

def cal_cos(x, y):
    # Lâp trình tại đây
    cos_sim = 0
    cos_sim = np.dot(x, y) / (np.linalg.norm(x) * np.linalg.norm(y))
    return round(cos_sim, 4)

x = np.array([1, 2, 3])
y = np.array([2, 3, 4])
z = np.array([-2, -2, 3])

print(cal_cos(x, y))
print(cal_cos(x, z))

0.9926
0.1945


# 2.1 Kích thước ma trận
Kích thước của na trận = [ số hàng x số cột ]

In [2]:
import numpy as np
v = np.array([[2, 4], [5, -7], [12, 5]])

In [3]:
v.shape

(3, 2)

In [4]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(a.shape)
b = np.array([[1, 2, 3]])

print(b.shape)


(3, 3)
(1, 3)


# 2.2 Scalar operations

# 2.3 Elementwise operations
Để có thể thực hiện phép Elementwise trên Matrix, các Matrix phải có cùng kích thước với nhau. Chúng ta sẽ thực hiện kết hợp các giá trị tương ứng với nhau từng vị trí các Matrix với nhau để tạo ra 1 Matrix mới

In [7]:
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[1, 2],
              [3, 4]])

print("a + b: \n", a + b)

a + b: 
 [[2 4]
 [6 8]]


# 2.4 Hadamard product
Matrix hadamard product sẽ thực hiện phép nhân elementwise.

In [8]:
a = np.array([[2, 3],
              [2, 43]])

b = np.array([[3, 4],
              [5, 6]])
# Uses python's multiply operator
a * b

array([[  6,  12],
       [ 10, 258]])

Trong python, chúng ta có thể sử dụng phép Hadamard giữa vector và matrix. Khí đó, Python sẽ sử dụng phương thức broadcasting (chúng ta sẽ tìm hiểu phươ thức này bên dưới).

# 2.5 Matrix multiplication (nhân ma trận) - Dot Product
Cho hai ma trận ***A( m × n ), B( n × p)***, tích của ma trận được ký hiệu là ***C = AB*** khi đó ***C*** có kích thước ***m × p***. Ma trận C được tạo thành được tính như hình dưới đây:

**Chú ý**: để nhân ma trạn số cột của ma trận thứ mhất phải bằng số hàng của ma trận thư hai.
Một số tính chất của ma trận:
- Phép nhân ma trận **không** có tính chất giao hoán.
- Phép nhân ma trận có tính kết hợp: ***ABC = (AB)C = A(BC)***
- Phép nhân ma trận có tính giao hoán: ***A(B + C) = AB + AC***
- Chuyển vị của một tích chuyển vị theo thứ tự ngược lại: (AB)T = B** **T × A** **T

In [9]:
A = np.array([[1, 7], [2, 4]])
B = np.array([[3, 3], [5, 2]])

np.dot(A, B)

array([[38, 17],
       [26, 14]])

In [10]:
A.dot(B)

array([[38, 17],
       [26, 14]])

In [11]:
np.dot(B, A)

array([[ 9, 33],
       [ 9, 43]])

# 2.6 Ma trận chuyển vị
Ví dụ: với M là ma trận ban đầu, T là ma trận chuyển vị.

Nếu A**T = A thì là một ma trận đổi **xưng**.

In [12]:
a = np.array([[1, 2],
              [3, 4]])
print(a.T)

[[1 3]
 [2 4]]


In [13]:
np.transpose(a)

array([[1, 3],
       [2, 4]])

# 2.7 Định thức

In [14]:
import numpy as np

In [1]:
import numpy as np
def exercise12(A, B):
    # Lập trình tại đây
    result = np.matmul(A.T, A)
    result = np.matmul(result, A)
    PreResult = np.matmul(B, B.T)
    result = np.matmul(result, PreResult)
    return result

A = np.array([[1, -1, 2 ],[2, 3, 4 ],[4, 1 , 5]])
B = np.array([[2, -1],[3, -4],[4, -5]])

print(exercise12(A, B))

[[ 4119  9786 12567]
 [ 2626  6269  8048]
 [ 6285 14940 19185]]


# 5. Tensor

In [2]:
a = np.array([[1, 2], [3, 4]])

In [3]:
t = np.array([[[1, 2], [3, 4]], [[1, 2], [3, 4]]])

In [5]:
t.shape

(2, 2, 2)

In [6]:
t2 = np.array([[[[1, 2], [3, 4]], [[1, 2], [3, 4]]], [[[1, 2], [3, 4]], [[1, 2], [3, 4]]]])

In [7]:
t2.shape

(2, 2, 2, 2)

In [9]:
t3 = np.array([[[[[1, 2], [3, 4]], [[1, 2], [3, 4]]], [[[1, 2], [3, 4]], [[1, 2], [3, 4]]]], [[[[1, 2], [3, 4]], [[1, 2], [3, 4]]], [[[1, 2], [3, 4]], [[1, 2], [3, 4]]]], [[[[1, 2], [3, 4]], [[1, 2], [3, 4]]], [[[1, 2], [3, 4]], [[1, 2], [3, 4]]]], [[[[1, 2], [3, 4]], [[1, 2], [3, 4]]], [[[1, 2], [3, 4]], [[1, 2], [3, 4]]]]])

In [10]:
t3.shape

(4, 2, 2, 2, 2)